### ISSUE TITLE
Windows, print preview broken in v2.0.2

### ISSUE THREAD

**Issue by 4tmorris** [repetier/Repetier-Host#368] opened 2017-07-30 12:54 UTC
Windows 7, since v2.0.2
Parts of the g code are not showing in the print preview. 
![rep_host](https://user-images.githubusercontent.com/22185615/28753565-f2ad41ce-752d-11e7-8283-d1298b7a6a71.png)

**Comment by repetier** [comment] 2017-07-30 14:09
If you used Slic3r Prusa Engine they are simply not there. We reverted back to 1.36.0 which does slice it correctly. SO please update to 2.0.4

**Comment by 4tmorris** [comment] 2017-08-01 14:01
That is what I am seeing with v2.0.4. with gcode generated by slic3r PE 1.36.0. 
![rep_host_204](https://user-images.githubusercontent.com/22185615/28828944-336b3e12-76ca-11e7-913d-5bc5f8b94ba0.png)

Here is the same gcode displayed by v2.0.1 
![rep_host_201](https://user-images.githubusercontent.com/22185615/28828951-3c6e31fe-76ca-11e7-8d26-fe51d81a74f2.png)

**Comment by repetier** [comment] 2017-08-01 14:44
We found a visualization bug. It is already fixed in 2.0.5 and now we also include Slic3r PE 1.36.2. There we could not reproduce it any more, so hopefully completely fixed.

**Closed by repetier** 2017-08-01 14:44 UTC
